# Generated by Django 5.1 on 2024-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('disponibility', models.BooleanField()),
                ('courses', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('lesson', models.CharField(max_length=100)),
                ('next_meet', models.CharField(max_length=100)),
            ],
        ),
    ]
