# Generated by Django 5.1 on 2024-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='matricule',
            field=models.CharField(max_length=15),
        ),
    ]
